# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::056843022100:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15943U4ZNC70Y
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::056843022100:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-21T11:27:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4349"
  uid: 4dbc751e-d811-4588-8eca-73d339b9b9c1
